98 goto cancellation takes more and more time
pollen-robotics/reachy2_sdk_server pull request #101
Opened 2024-01-25 10:57 UTC by glannuzel

- When a goal is cancelled, we move it to the outdated_goal_handles
- Every 30seconds we clean the goal_handles dict to remove cancelled, succeeded or aborted goto

2024-01-25 11:30 UTC, RemiFabre commented
Can you please explain how this was tested? And if possible, share a procedure to test it?

2024-01-25 11:47 UTC, glannuzel commented
Tested using pytest on reachy2-sdk, especially the following tests : 
https://github.com/pollen-robotics/reachy2-sdk/blob/develop/tests/test_advanced_goto_functions.py

2024-01-30 10:41 UTC, FabienDanieau requested changes
Tests are passing. I'd recommend some changes regarding the usage of the lock + minor stuffs

2024-01-30 10:41 UTC, FabienDanieau commented on reachy_sdk_server/reachy_sdk_server/grpc_server/goto.py
> +                    if int(self.goal_handles[goal_id].status) > 3:
Use the enum GoalStatus instead of 3 for a better readability

2024-01-30 10:41 UTC, FabienDanieau commented on reachy_sdk_server/reachy_sdk_server/grpc_server/goto.py
> +            if goal_id_int in self.goal_manager.goal_handles and self.goal_manager.goal_handles[goal_id_int].status in [0, 1]
Also here insteand of 0,1 use goalstatus enum

2024-01-30 10:41 UTC, FabienDanieau commented on reachy_sdk_server/reachy_sdk_server/grpc_server/goto.py
>          with self.lock:
I don't think this lock is useful

2024-01-30 10:41 UTC, FabienDanieau commented on reachy_sdk_server/reachy_sdk_server/grpc_server/goto.py
> +            self.goal_manager.sideline_goal_handle(goal_id)
This call goes "inside" the lock so an item can be poped twice.
I would remove this call since the thread will call it automatically

2024-01-30 10:41 UTC, FabienDanieau commented on reachy_sdk_server/reachy_sdk_server/grpc_server/goto.py
> +    def sideline_goal_handle(self, goal_id: int) -> None:
follow up to my previous comment about the lock. Make this function "private" -> _sideline_goal_handle
It will be called by the thread only

2024-01-30 10:41 UTC, FabienDanieau commented on reachy_sdk_server/reachy_sdk_server/grpc_server/goto.py
> +    def sideline_goal_handle(self, goal_id: int) -> None:
make remove_goal_handle private also -> _remove_goal_handle

2024-01-30 10:41 UTC, FabienDanieau commented on reachy_sdk_server/reachy_sdk_server/grpc_server/goto.py
> +        goal_handle = self.goal_handles.get(goal_id, None)
add a lock around this function to prevent GoToServicer to get during the _sort_goal_handles
Same for store_goal_handle

2024-01-30 10:41 UTC, FabienDanieau commented on reachy_sdk_server/reachy_sdk_server/grpc_server/goto.py
> +        self._hoarder_collector.daemon = True
you add daemon=True when creating the thread above
self._hoarder_collector = threading.Thread(target=self._sort_goal_handles, daemon=True)

2024-01-31 09:54 UTC, FabienDanieau approved these changes
re-tested works fine.

2024-01-31 10:33 UTC, merged

2024-02-01 12:46 UTC, RemiFabre commented
:+1: